dist: trusty
language: php
php:
  #- 5.4
  #- 5.5
  #- 5.6
  - 7.0

env:
  #- TEST_SUITE=marketplate_eqp
  - TEST_SUITE=unit
  #- TEST_SUITE=ecg_coding_standards

before_script:
  - sleep 30

script:
  - cd ..
  - sh -c "if [ '$TEST_SUITE' = 'marketplate_eqp' ]; then composer config --global repositories.magento-eqp git https://github.com/magento/marketplace-eqp && composer require magento/marketplace-eqp && vendor/squizlabs/php_codesniffer/scripts/phpcs --config-set installed_paths /home/travis/build/mailchimp/vendor/magento/marketplace-eqp/ && vendor/squizlabs/php_codesniffer/scripts/phpcs -n --standard="MEQP1" ./mc-magento/; fi"
  - sh -c "if [ '$TEST_SUITE' = 'ecg_coding_standards' ]; then composer require magento-ecg/coding-standard && composer require "squizlabs/php_codesniffer=2.6.2" && vendor/squizlabs/php_codesniffer/scripts/phpcs --config-set installed_paths /home/travis/build/mailchimp/vendor/magento-ecg/coding-standard && vendor/squizlabs/php_codesniffer/scripts/phpcs -n --standard="Ecg" ./mc-magento/; fi"
  - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then wget http://ebizmartsbackup.s3.amazonaws.com/magento-1.9.2.4-2016-02-23-06-07-06.tar.bz2 && tar xjf magento-1.9.2.4-2016-02-23-06-07-06.tar.bz2 && /bin/cp -r mc-magento/* . && cd tests/unit && wget https://phar.phpunit.de/phpunit-4.8.phar && php phpunit-4.8.phar; fi"

#notifications:
#  slack: ebizmarts:DqCqxnqWzW55zoFU069hxs1T
